name: Update template

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Configure Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install and run copier update
        run: |
          python -m pip install -U pip
          python -m pip install -U copier
          python -m copier --force update
      - name: Create a pull request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Updating Copier template
          branch: update-template
          delete-branch: true
          title: Updating Copier template
          body: |
            Automatically updating the Copier template

            **Maintainers should close and then re-open this PR to get the tests to run.**
